# Generated by Django 5.1.3 on 2024-12-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Edad del individuo.')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Género del individuo.', max_length=10)),
                ('weight', models.FloatField(help_text='Peso en kilogramos.')),
                ('height', models.FloatField(help_text='Altura en metros.')),
                ('max_bpm', models.IntegerField(help_text='Frecuencia cardíaca máxima.')),
                ('avg_bpm', models.IntegerField(help_text='Frecuencia cardíaca promedio.')),
                ('resting_bpm', models.IntegerField(help_text='Frecuencia cardíaca en reposo.')),
                ('session_duration', models.FloatField(help_text='Duración de la sesión en horas.')),
                ('calories_burned', models.FloatField(help_text='Calorías quemadas durante el ejercicio.')),
                ('workout_type', models.CharField(help_text='Tipo de ejercicio realizado.', max_length=50)),
                ('fat_percentage', models.FloatField(help_text='Porcentaje de grasa corporal.')),
                ('water_intake', models.FloatField(help_text='Consumo de agua en litros.')),
                ('workout_frequency', models.IntegerField(help_text='Frecuencia de entrenamiento por semana.')),
                ('experience_level', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], help_text='Nivel de experiencia.', max_length=50)),
                ('bmi', models.FloatField(help_text='Índice de Masa Corporal proporcionado en el CSV.')),
            ],
        ),
    ]
